### PR TITLE
Refactor: SQLAlchemy, MySQL, and new directory structure

### PR DESCRIPTION
**Pull request by dnascimb**
You can perform the user functions (including password hashing), however, service ticket creation appears to need to be reworked, with what we now know so it isn't functioning (you can still bring the screen up).

I did look at making the database credentials configurable, and it was one of those things that would take a solid afternoon to get right but then we'd have it forever. I will do this in the future. This one merge is big enough and will get you moving.

Just give me a thumbs up and I'll merge this.

### CODE REVIEW

**Comment by edcomstock** [comment]
Ok, heading to Boston today, I'll give the changes a look at lunch.  Good
stuff.

**Comment by edcomstock** [comment]
Clear to merge sir!

**Comment by dnascimb** [comment]
We could roll exceptions into a standard function but unless the code gets crazy verbose, it probably isn't necessary. Meh, one of those blurry lines in programming.

Thanks Ed

**Comment by edcomstock** [comment]
Exquisite.  Apparently I do have uncommitted changes because I'd started on
an employee management screen that I'd forgotten about.  Maybe I'll 'stash'
it, or maybe I'll just copy it off to the side and overwrite with your
changes and drop it back in again.  It's only a couple files, and things
need to change anyway with the new structure of MSC/MSC.

**Pull request merged**
